TnsCMS.Web/Areas/Admin/Models/Search/AdminSearchQuery.cs
using System;

namespace MrCMS.Web.Areas.Admin.Models.Search
{
    public class AdminSearchQuery
    {
        public AdminSearchQuery()
        {
            Page = 1;
        }

        public int Page { get; set; }

        public string Term { get; set; }
        public string Type { get; set; }

        public DateTime? CreatedOnFrom { get; set; }
        public DateTime? CreatedOnTo { get; set; }
    }
}

TnsCMS.Web/Areas/Admin/Models/Search/AdminSearchResult.cs
using MrCMS.Entities;
using MrCMS.Helpers;
using MrCMS.Search.Models;

namespace MrCMS.Web.Areas.Admin.Models.Search
{
    public class AdminSearchResult
    {
        private readonly UniversalSearchItem _item;
        private readonly SystemEntity _entity;

        public AdminSearchResult(UniversalSearchItem item, SystemEntity entity)
        {
            _item = item;
            _entity = entity;
        }

        public string ActionUrl { get { return _item.ActionUrl; } }
        public string DisplayName { get { return _item.DisplayName; } }
        public SystemEntity Entity { get { return _entity; } }
        public string Type
        {
            get
            {
                var typeByName = TypeHelper.GetTypeByName(_item.SystemType);
                return typeByName == null ? "" : typeByName.Name.BreakUpString(); 
            }
        }
    }
}

TnsCMS.Web/Areas/Admin/Models/Search/AdminWebpageSearchQuery.cs
using System;
using System.ComponentModel;
using Lucene.Net.Documents;
using Lucene.Net.Index;
using Lucene.Net.QueryParsers;
using Lucene.Net.Search;
using MrCMS.Entities.Documents.Web;
using MrCMS.Entities.Indexes;
using MrCMS.Indexing;
using MrCMS.Indexing.Definitions;
using MrCMS.Indexing.Management;
using MrCMS.Indexing.Utils;

namespace MrCMS.Web.Areas.Admin.Models.Search
{
    public class AdminWebpageSearchQuery
    {
        public AdminWebpageSearchQuery()
        {
            Page = 1;
        }
        public string Term { get; set; }
        public int Page { get; set; }
        public Webpage Parent { get; set; }
        public string Type { get; set; }
        [DisplayName("Created On From")]
        public DateTime? CreatedOnFrom { get; set; }
        [DisplayName("Created On To")]
        public DateTime? CreatedOnTo { get; set; }

        public Query GetQuery()
        {
            if (String.IsNullOrWhiteSpace(Term) && String.IsNullOrWhiteSpace(Type) && !CreatedOnTo.HasValue && !CreatedOnFrom.HasValue && Parent == null)
                return new MatchAllDocsQuery();

            var booleanQuery = new BooleanQuery();
            if (!String.IsNullOrWhiteSpace(Term))
            {
                var indexDefinition = IndexingHelper.Get<AdminWebpageIndexDefinition>();
                var analyser = indexDefinition.GetAnalyser();
                var parser = new MultiFieldQueryParser(Lucene.Net.Util.Version.LUCENE_30, indexDefinition.SearchableFieldNames, analyser);
                Query query = Term.SafeGetSearchQuery(parser, analyser);

                booleanQuery.Add(query, Occur.MUST);
            }
            if (CreatedOnFrom.HasValue || CreatedOnTo.HasValue)
                booleanQuery.Add(GetDateQuery(), Occur.MUST);
            if (!string.IsNullOrEmpty(Type))
                booleanQuery.Add(new TermQuery(new Term(FieldDefinition.GetFieldName<TypeFieldDefinition>(), Type)),
                                 Occur.MUST);
            if (Parent != null)
                booleanQuery.Add(
                    new TermQuery(new Term(FieldDefinition.GetFieldName<ParentIdFieldDefinition>(), Parent.Id.ToString())), Occur.MUST);

            return booleanQuery;
        }
        private Query GetDateQuery()
        {
            return new TermRangeQuery(FieldDefinition.GetFieldName<CreatedOnFieldDefinition>(),
                CreatedOnFrom.HasValue
                    ? DateTools.DateToString(CreatedOnFrom.Value, DateTools.Resolution.SECOND)
                    : null,
                CreatedOnTo.HasValue
                    ? DateTools.DateToString(CreatedOnTo.Value, DateTools.Resolution.SECOND)
                    : null, CreatedOnFrom.HasValue, CreatedOnTo.HasValue);
        }
    }
}

TnsCMS.Web/Areas/Admin/Models/Search/QuickSearchResult.cs
namespace MrCMS.Web.Areas.Admin.Models.Search
{
    public class QuickSearchResult
    {
        public int id { get; set; }
        public string value { get; set; }

        public string url { get; set; }

        //public string CreatedOn { get; set; }
        //public string Type { get; set; }
    }
}

TnsCMS.Web/Areas/Admin/Controllers/SearchController.cs
using System.Web.Mvc;
using MrCMS.Web.Areas.Admin.Models.Search;
using MrCMS.Web.Areas.Admin.Services.Search;
using MrCMS.Website.Controllers;

namespace MrCMS.Web.Areas.Admin.Controllers
{
    public class SearchController : MrCMSAdminController
    {
        private readonly IAdminSearchService _adminSearchService;

        public SearchController(IAdminSearchService adminSearchService)
        {
            _adminSearchService = adminSearchService;
        }

        [HttpGet]
        public ActionResult Index(AdminSearchQuery model)
        {
            ViewData["results"] = _adminSearchService.Search(model);

            return View(model);
        }
    }
}

TnsCMS.Web/Areas/Admin/Views/Search/GetBreadCrumb.cshtml
@model IEnumerable<MrCMS.Entities.Documents.Document>
@if (Model != null && Model.Any())
{
    <ul class="breadcrumb">
        <li><a href="/Admin/Search?parent=0">Top</a> <span class="divider">/</span></li>
        @foreach (var item in Model.ToList())
        {
            <li><a href="@item.UrlSegment&amp;type=@Request.QueryString["type"]">@item.Name</a> <span class="divider">/</span></li>
        }
    </ul>
}

TnsCMS.Web/Areas/Admin/Views/Search/Index.cshtml
@using System.Drawing
@using MrCMS.Entities.Documents.Media
@using MrCMS.Helpers
@using MrCMS.Media
@using MrCMS.Paging
@using MrCMS.Services.FileMigration
@using MrCMS.Web.Areas.Admin.Helpers
@using MrCMS.Web.Areas.Admin.Models.Search
@model MrCMS.Web.Areas.Admin.Models.Search.AdminSearchQuery
@{
    var results = ViewData["results"] as IPagedList<AdminSearchResult>;
    List<SelectListItem> typeOptions = UniversalSearchHelper.GetOptions();
}
@using (Html.BeginForm("Index", "Search", FormMethod.Get))
{
    <fieldset>
        <legend>
            Search @(!string.IsNullOrWhiteSpace(Model.Term) ? " - " + Model.Term : "")
            <span class="btn-group  display-inline  pull-right">
                <input type="submit" value="Search" class="btn btn-primary" />
            </span>
        </legend>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(x => x.Term)
                    @Html.TextBoxFor(x => x.Term, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.Term)
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(x => x.CreatedOnFrom)
                    @Html.TextBoxFor(x => x.CreatedOnFrom, new {@class = "date-time-picker form-control"})
                    @Html.ValidationMessageFor(x => x.CreatedOnFrom)
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(x => x.Type)
                    @Html.DropDownListFor(x => x.Type, typeOptions, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.Type)
                </div>

            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(x => x.CreatedOnTo)
                    @Html.TextBoxFor(x => x.CreatedOnTo, new {@class = "date-time-picker form-control"})
                    @Html.ValidationMessageFor(x => x.CreatedOnTo)
                </div>
            </div>
        </div>
        @Html.ValidationSummary()

    </fieldset>
}

<div id="search-results">
    @if (results == null || !results.Any())
    {
        <p>No documents could be found matching your search term</p>
    }
    else
    {
        <table class="table table-striped">
            <tr>
                <th class="col-lg-8">Page</th>
                <th class="col-lg-4">Type</th>
            </tr>
            @foreach (AdminSearchResult result in results)
            {
                <tr>
                    <td>
                        <a href="@result.ActionUrl" class="">
                            @if (result.Entity is MediaFile)
                            {
                                var file = result.Entity as MediaFile;
                                if (file.IsImage())
                                {
                                    @Html.RenderImage(file.FileUrl, new Size(100, 100))
                                }
                                else
                                {
                                    <i class="@file.FileExtension.GetIconClass()"> </i>
                                }
                                <br />
                            }
                            <strong>@result.DisplayName</strong>
                        </a>
                        
                        <br />
                        <p>Last updated on @result.Entity.UpdatedOn</p>
                    </td>
                    <td>@result.Type</td>
                </tr>
            }
        </table>
        @Html.Pager(results, "Index", page => new {page})
    }
</div>