TnsCMS.Web/Areas/Admin/Controllers/MessageTemplatePreviewController.cs
using System.Web.Mvc;
using MrCMS.Web.Areas.Admin.Services;
using MrCMS.Website.Controllers;

namespace MrCMS.Web.Areas.Admin.Controllers
{
    public class MessageTemplatePreviewController : MrCMSAdminController
    {
        private readonly IMessageTemplatePreviewService _messageTemplatePreviewService;

        public MessageTemplatePreviewController(IMessageTemplatePreviewService messageTemplatePreviewService)
        {
            _messageTemplatePreviewService = messageTemplatePreviewService;
        }

        public ViewResult Get(string type)
        {
            return View(_messageTemplatePreviewService.GetTemplate(type));
        }

        public PartialViewResult Preview(string type, int id)
        {
            return PartialView(_messageTemplatePreviewService.GetPreview(type, id));
        }
    }
}

TnsCMS.Web/Areas/Admin/Views/MessageTemplatePreview/Get.cshtml
@using MrCMS.Helpers
@model MrCMS.Messages.MessageTemplate
@{
    var typeInfo = new { type = Model.GetType().FullName };
}
@using (Html.BeginForm("Preview", "MessageTemplatePreview", typeInfo, FormMethod.Post, new { id = "preview-message-form", style = "display:inline;" }))
{
    <div style="min-height: 400px">
        <h1 class="page-header">
            @Resource("Admin Message Template Preview Title", "Preview message template")
            <span class="btn-group  display-inline  pull-right">
                @Html.ActionLink("Back to list", "Index", "MessageTemplate", null, new { @class = "btn btn-default" })
                @Html.ActionLink("Edit", "Edit", "MessageTemplate", typeInfo, new { @class = "btn btn-default" })
                <input type="submit" class="btn btn-primary" value="@Resource("Preview")" />
            </span>
        </h1>

        <div class="form-group">
            @Html.Label("id", @Model.ModelType.Name.BreakUpString() + " Id")
            @Html.TextBox("id", "1", new { @class = "form-control" })
        </div>
        <hr />

        <div id="preview">
        </div>
    </div>
}

@{ Html.IncludeScript("~/Areas/Admin/Content/Scripts/mrcms/preview-message-template.js");}

TnsCMS.Web/Areas/Admin/Views/MessageTemplatePreview/Preview.cshtml
@model MrCMS.Entities.Messaging.QueuedMessage

@if (Model != null)
{
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(x => x.FromAddress)
                @Html.DisplayFor(x => x.FromAddress)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.FromName)
                @Html.DisplayFor(x => x.FromName)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Cc)
                @Html.DisplayFor(x => x.Cc)
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(x => x.ToAddress)
                @Html.DisplayFor(x => x.ToAddress)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.ToName)
                @Html.DisplayFor(x => x.ToName)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Bcc)
                @Html.DisplayFor(x => x.Bcc)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                @Html.LabelFor(x => x.Subject)
                @Html.DisplayFor(x => x.Subject)
                @Html.ValidationMessageFor(x => x.Subject)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                @Html.LabelFor(x => x.Body)
                @if (Model.IsHtml)
                {
                    @Html.Raw(Model.Body)
                }
                else
                {
                    @Model.Body
                }
            </div>
        </div>
    </div>
}
else
{
    <p>
        Sorry, but we were unable to preview this template for this id
    </p>
}