TnsCMS.Web/Areas/Admin/Controllers/LogController.cs
using System.Web.Mvc;
using MrCMS.Logging;
using MrCMS.Web.Areas.Admin.Services;
using MrCMS.Website.Controllers;

namespace MrCMS.Web.Areas.Admin.Controllers
{
    public class LogController : MrCMSAdminController
    {
        private readonly ILogAdminService _adminService;

        public LogController(ILogAdminService adminService)
        {
            _adminService = adminService;
        }

        [HttpGet]
        public ViewResult Index(LogSearchQuery searchQuery)
        {
            ViewData["site-options"] = _adminService.GetSiteOptions();
            ViewData["logs"] = _adminService.GetEntriesPaged(searchQuery);
            return View(searchQuery);
        }

        public ViewResult Show(Log entry)
        {
            return View(entry);
        }

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult Delete_Get()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Delete()
        {
            _adminService.DeleteAllLogs();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("DeleteLog")]
        public ActionResult DeleteLog_Get(Log log)
        {
            return PartialView(log);
        }

        [HttpPost]
        public ActionResult DeleteLog(Log log)
        {
            _adminService.DeleteLog(log);

            return RedirectToAction("Index");
        }
    }
}

TnsCMS.Web/Areas/Admin/Views/Log/Delete.cshtml
@using MrCMS.Helpers
@{ Layout = "~/Areas/Admin/Views/Shared/_LayoutPopup.cshtml";}
@using (Html.BeginForm("Delete", "Log", FormMethod.Post, new { style = "display:inline;" }))
{
    <fieldset>
        <legend>@Resource("Admin Logs Delete All Title", "Delete all logs")
                <span class="btn-group  display-inline  pull-right">
                    <input type="submit" class="btn btn-danger" value="@Resource("Delete")" />
                </span>
        </legend>
        @Html.InfoBlock(Resource("Heads up") + "!", Resource("Admin Delete Info Warning", "Deleting this cannot be undone."), AlertType.danger)
    </fieldset>
}

TnsCMS.Web/Areas/Admin/Views/Log/DeleteLog.cshtml
@using MrCMS.Helpers
@model MrCMS.Logging.Log
@{ Layout = "~/Areas/Admin/Views/Shared/_LayoutPopup.cshtml";}
@using (Html.BeginForm("DeleteLog", "Log", new { id = Model.Id }, FormMethod.Post, new { style = "display:inline;" }))
{
    <fieldset>
        <legend>@Resource("Admin Logs Delete Title", "Delete log")
                <span class="btn-group  display-inline  pull-right">
                    <input type="submit" class="btn btn-danger" value="@Resource("Delete")"/>
                </span>
        </legend>
        @Html.InfoBlock(Resource("Heads up") + "!", Resource("Admin Delete Info Warning", "Deleting this cannot be undone."), AlertType.danger)
    </fieldset>
}

TnsCMS.Web/Areas/Admin/Views/Log/Index.cshtml
@using System
@using System.Collections.Generic
@using System.Linq
@using MrCMS.Helpers
@using MrCMS.Logging
@using MrCMS.Paging
@model LogSearchQuery
@{
    ViewBag.Title = "Logs";
    var logs = ViewData["logs"] as IPagedList<Log> ?? PagedList<Log>.Empty;
    var siteOptions = ViewData["site-options"] as List<SelectListItem> ?? new List<SelectListItem>();
}
@using (Html.BeginForm("Index", "Log", FormMethod.Get))
{
    <fieldset>
        <legend>
            @Resource("Admin Logs Title", "Logs")
            <span class="btn-group display-inline pull-right">
                <a href="@Url.Action("Delete", "Log")" class="btn btn-danger" data-toggle="fb-modal">@Resource("Admin Logs Delete Logs Button", "Delete logs")</a>
                <input type="submit" class="btn btn-primary" value="@Resource("Search")" />
            </span>
        </legend>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(query => query.Type)
                    @Html.DropDownListFor(query => query.Type, Enum.GetValues(typeof(LogEntryType)).OfType<LogEntryType>().BuildSelectItemList(type => type.ToString(), type => type.ToString(), type => type == Model.Type, "All"), new { @class = "form-control" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(query => query.SiteId)
                    @Html.DropDownListFor(query => query.SiteId, siteOptions, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(query => query.From)
                    @Html.TextBoxFor(query => query.From, new { @class = "date-time-picker form-control" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(query => query.To)
                    @Html.TextBoxFor(query => query.To, new { @class = "date-time-picker form-control" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(query => query.Message)
                    @Html.TextBoxFor(query => query.Message, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(query => query.Detail)
                    @Html.TextBoxFor(query => query.Detail, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="row">

        </div>
    </fieldset>
}

@if (logs.Count == 0)
{
    @Resource("Admin Logs No Logs", "No logs")
        }
else
{
    <table class="table table-striped table-condensed" style="overflow: scroll">
        <thead>
            <tr>
                <th>
                    @Resource("Date")
                </th>
                <th>
                    @Resource("Site")
                </th>
                <th>
                    @Resource("Message")
                </th>
                <th>
                    @Resource("Type")
                </th>
                <th>
                    @Resource("Actions")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var entry in logs)
            {
                <tr>
                    <td>
                        @entry.CreatedOn.ToString("dd/MM/yyyy HH:mm")
                    </td>
                    <td>
                        @entry.SiteName
                    </td>
                    <td>
                        @entry.Message
                    </td>
                    <td>
                        @entry.Type
                    </td>
                    <td>
                        @Html.ActionLink(Resource("Show"), "Show", new { id = entry.Id }, new { @class = "btn btn-xs btn-default" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@Html.Pager(logs, "Index", i => new { page = i })

TnsCMS.Web/Areas/Admin/Views/Log/Show.cshtml
@model MrCMS.Logging.Log
@{
    ViewBag.Title = "View Log #" + Model.Id;
}

<h1 class="page-header">
    @Resource("Admin Logs Log Title", "Log") #@Model.Id
    <span class="btn-group  display-inline  pull-right">
        @Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-default" })
        <a href="@Url.Action("DeleteLog", "Log", new { Model.Id })" class="btn btn-danger" data-toggle="fb-modal">@Resource("Delete")</a>
    </span>
</h1>
<table class="table table-striped table-condensed">
    <tbody>
        <tr>
            <td class="col-lg-2">
                @Resource("Type")
            </td>
            <td class="col-lg-10">
                @Model.Type
            </td>
        </tr>
        <tr>
            <td>
                @Resource("Created on")
            </td>
            <td>
                @Model.CreatedOn
            </td>
        </tr>
        <tr>
            <td>
                @Resource("Site")
            </td>
            <td>
                @Model.SiteName
            </td>
        </tr>
        <tr>
            <td>
                @Resource("Message")
            </td>
            <td>
                @Model.Message
            </td>
        </tr>
        <tr>
            <td>
                @Resource("Detail")
            </td>
            <td>
                @Html.Raw(Model.DetailFormatted)
            </td>
        </tr>
    </tbody>
</table>
@if (Model.Error != null)
{
    <h4>@Resource("Admin Logs Server Variables", "Server Variables")</h4>
    <div style="overflow: scroll">
        <table class="table table-striped table-condensed">
            <thead>
                <tr>
                    <th class="col-lg-2">
                        @Resource("Key")
                    </th>
                    <th class="col-lg-10">
                        @Resource("Value")
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var key in Model.Error.ServerVariables.AllKeys)
                {
                    <tr>
                        <td>
                            @key
                        </td>
                        <td>
                            @Model.Error.ServerVariables[key]
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
}